"""change 'done'

Revision ID: 0ca08c4f5a24
Revises: 9f394242a091
Create Date: 2024-02-21 20:04:52.580067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca08c4f5a24'
down_revision = '9f394242a091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
