"""change 'done'

Revision ID: 5b484d532e27
Revises: 0ca08c4f5a24
Create Date: 2024-02-21 20:19:00.463944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b484d532e27'
down_revision = '0ca08c4f5a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('importance',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('importance',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('done',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
