"""add column in tasks

Revision ID: 830524ac4651
Revises: 87b8cd7ca8fb
Create Date: 2024-02-20 23:30:38.620717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830524ac4651'
down_revision = '87b8cd7ca8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('importance')

    # ### end Alembic commands ###
